import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { Check, Download, ExternalLink, QrCode, Share2, Smartphone, X } from 'lucide-react';

const shareTitle = 'Little Stars Learning Adventure';
const shareText = 'Play Little Stars Learning Adventure — a fun educational game for young children!';

export function ShareButton({ compact = false }: { compact?: boolean }) {
  const [copied, setCopied] = useState(false);
  const [open, setOpen] = useState(false);
  const url = typeof window === 'undefined' ? '' : window.location.href;
  const copy = async () => { try { await navigator.clipboard.writeText(url); } catch { const input = document.createElement('textarea'); input.value = url; document.body.appendChild(input); input.select(); document.execCommand('copy'); input.remove(); } setCopied(true); setTimeout(() => setCopied(false), 2200); };
  const share = async () => { if (navigator.share) { try { await navigator.share({ title: shareTitle, text: shareText, url }); } catch { /* User cancelled the native share sheet. */ } } else { await copy(); setOpen(true); } };
  return <div className="share-control"><button className={compact ? 'icon-btn share-btn' : 'secondary-btn'} aria-label="Share game" onClick={share}>{copied ? <Check size={18} /> : <Share2 size={18} />}<span>{compact ? '' : copied ? 'Game link copied!' : 'Share Game'}</span></button>{open && <div className="share-popover"><button onClick={copy}><Check size={15} /> {copied ? 'Game link copied!' : 'Copy Link'}</button><a href={`https://wa.me/?text=${encodeURIComponent(`${shareText} ${url}`)}`} target="_blank" rel="noreferrer"><ExternalLink size={15} /> WhatsApp</a><button className="popover-close" onClick={() => setOpen(false)}><X size={14} /></button></div>}</div>;
}

type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }> };
export function InstallButton() { const [prompt, setPrompt] = useState<InstallPrompt | null>(null); const [showIos, setShowIos] = useState(false); useEffect(() => { const handler = (event: Event) => { event.preventDefault(); setPrompt(event as InstallPrompt); }; window.addEventListener('beforeinstallprompt', handler); const dismissed = localStorage.getItem('little-stars-install-dismissed') === '1'; const ios = /iphone|ipad|ipod/i.test(navigator.userAgent) && !(window.navigator as Navigator & { standalone?: boolean }).standalone; if (ios && !dismissed) setShowIos(true); return () => window.removeEventListener('beforeinstallprompt', handler); }, []); if (!prompt && !showIos) return null; const install = async () => { if (prompt) { await prompt.prompt(); await prompt.userChoice; setPrompt(null); } else setShowIos(true); }; return <><button className="install-btn" onClick={install}><Download size={16} /> Install App</button>{showIos && <div className="install-tip"><div><Smartphone size={18} /><strong>Add Little Stars to your Home Screen</strong><p>Tap Share, then select <b>Add to Home Screen</b>.</p></div><button aria-label="Dismiss install instructions" onClick={() => { localStorage.setItem('little-stars-install-dismissed', '1'); setShowIos(false); }}><X size={16} /></button></div>}</>; }

export function QRShare() { const [dataUrl, setDataUrl] = useState(''); const [open, setOpen] = useState(false); useEffect(() => { QRCode.toDataURL(window.location.href, { width: 220, margin: 2, color: { dark: '#00658d', light: '#ffffff' } }).then(setDataUrl).catch(() => setDataUrl('')); }, []); return <><button className="secondary-btn qr-btn" onClick={() => setOpen(true)}><QrCode size={17} /> Show QR code</button>{open && <div className="modal-backdrop"><div className="qr-modal"><button className="modal-close" onClick={() => setOpen(false)}><X /></button><QrCode size={28} color="#00658d" /><h2>Open on another phone</h2><p>Scan this code to play Little Stars.</p>{dataUrl ? <img src={dataUrl} alt="QR code for Little Stars Learning Adventure" /> : <p>QR code is preparing…</p>}<button className="primary-btn" onClick={() => setOpen(false)}>Done</button></div></div>}</>; }

export function UpdateNotice() { const [ready, setReady] = useState(false); useEffect(() => { const handler = () => setReady(true); window.addEventListener('little-stars-update', handler); return () => window.removeEventListener('little-stars-update', handler); }, []); if (!ready) return null; return <div className="update-notice"><span>✨ A fresh learning adventure is ready.</span><button onClick={() => window.location.reload()}>Update</button></div>; }

export function PrivacyPage({ onBack }: { onBack: () => void }) { return <section className="page privacy-page"><button className="back-btn" onClick={onBack}>← Back</button><div className="section-heading"><p className="eyebrow">For grown-ups</p><h2>Privacy at Little Stars</h2><p>A simple, private learning space for children.</p></div><article className="privacy-card"><h3>No ads. No tracking.</h3><p>Little Stars Learning Adventure does not show advertisements, use analytics trackers, sell data, or include public chat or leaderboards.</p><h3>Progress stays on this device</h3><p>Child profiles, progress, rewards, and parent assignments are stored in this browser’s local storage. They are not synchronized between phones or browsers and are not sent to a server.</p><h3>Parent controls</h3><p>The Parent Area is protected by the parent PIN configured for this demo. Please keep your device and PIN private.</p><h3>Sharing</h3><p>Share links contain only the public game URL. A child’s name, age, progress, rewards, and PIN are never added to shared links.</p></article></section>; }
