import { CircleHelp, Volume2 } from 'lucide-react';
import type { LanguageMode, VoicePreferences } from './storage';
import type { Task } from './taskEngine';
import { useVoice, VoiceControls } from './voice';
import { uiText } from './translations';

export function CountStarsGame({ task, options, language, index, total, result, transitioning, preferences, onAnswer, onReplay }: { task: Task; options: Task['options']; language: LanguageMode; index: number; total: number; result: boolean | null; transitioning: boolean; preferences: VoicePreferences; onAnswer: (optionId: string) => void; onReplay: () => void }) {
  const voice = useVoice();
  const number = Math.max(1, Math.min(index + 1, total)); const count = task.visualCount || 1; const stars = Array.from({ length: count }, (_, starIndex) => <span className="count-star" key={`${task.id}-star-${starIndex}`} aria-hidden="true">★</span>);
  return <section className="page game-page count-game-page" dir={language === 'ur' ? 'rtl' : 'ltr'}><div className="game-top"><span className="game-stars">{number} / {total}</span><div className="question-progress">{Array.from({ length: total }, (_, i) => <span className={i < number ? 'filled' : ''} key={i} />)}</div></div><div className="game-card"><div className="instruction-row"><span>{language === 'ur' ? 'ستارے گنیں' : 'Count the Stars'}</span><span>{number} / {total}</span><button className="round-btn" onClick={() => voice.stop()} aria-label={uiText(language, 'stop')}>■</button></div><div className={`count-star-display count-${count}`} aria-label={`${count} ${language === 'ur' ? 'ستارے' : 'stars'}`}>{stars}</div><h2>{language === 'ur' ? 'ستارے گنیں اور درست عدد منتخب کریں۔' : 'Count the stars and choose the correct number.'}</h2><p className="count-question">{language === 'ur' ? 'تصویر میں کتنے ستارے ہیں؟' : 'How many stars do you see?'}</p><p className="hint"><CircleHelp size={17} /> {language === 'ur' ? 'ہر ستارہ غور سے گنیں۔' : 'Count each star carefully.'}</p><div className="option-grid count-options">{options.map((option) => <button key={option.id} className={`picture-option count-option ${result !== null && option.id === task.answerId ? 'correct-option' : ''}`} onClick={() => onAnswer(option.id)} disabled={result !== null || transitioning}><strong>{language === 'ur' ? option.wordUr : option.word}</strong></button>)}</div>{result !== null && <div className={`feedback ${result ? 'good' : 'try-again'}`}><span>{result ? '🌟' : '💛'}</span><div><p>{result ? (language === 'ur' ? `شاباش! آپ نے ${task.options.find((option) => option.id === task.answerId)?.wordUr} ستارے درست گنے۔` : `Great counting! You found ${task.numberValue} stars.`) : (language === 'ur' ? 'ستارے دوبارہ گنیں۔' : 'Let’s count the stars again.')}</p></div></div>}</div><div className="game-footer"><VoiceControls language={language} preferences={preferences} compact={false} /><button className="text-btn" onClick={onReplay}><Volume2 size={17} /> {uiText(language, 'listenAgain')}</button></div>{import.meta.env.DEV && <small className="voice-note" data-testid="voice-diagnostic">language={language} · question={task.id} · currentIndex={index} · total={total}</small>}</section>;
}
