import { useEffect, useRef, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, CircleHelp, Coins, LockKeyhole, Map, Play, RotateCcw, ShieldCheck, Star, Volume2, VolumeX, X } from 'lucide-react';
import { hashPin, loadStore, newProfile, saveStore, type ClassLevel, type LanguageMode, type Profile, type Store } from './storage';
import { activitiesFor, taskText, type Task } from './taskEngine';
import { buildShuffledSession, type ShuffledQuestion } from './optionShuffle';
import { AdventureBoard, ParentDashboard, ProfileForm, ProfilePicker } from './profileFeatures';
import { InstallButton, PrivacyPage, QRShare, ShareButton, UpdateNotice } from './appFeatures';
import { VoiceControls, VoiceProvider, useVoice } from './voice';
import { ParentVoiceSettings } from './voiceFeatures';
import { MemoryGame } from './memoryGame';
import { CountStarsGame } from './countStarsGame';
import { uiText } from './translations';
import './styles.css';

type Screen = 'profiles' | 'profile-form' | 'privacy' | 'splash' | 'levels' | 'map' | 'adventure' | 'game' | 'complete' | 'parent';
const levels: { name: ClassLevel; age: string; color: string; icon: string; description: string }[] = [
  { name: 'Play Group', age: '2–3 years', color: 'coral', icon: '🌱', description: 'Discover shapes, colors & sounds' }, { name: 'Pre-Nursery', age: '3–4 years', color: 'yellow', icon: '🌈', description: 'Build early words & numbers' }, { name: 'Nursery', age: '4–5 years', color: 'blue', icon: '🚀', description: 'Practice letters & patterns' }, { name: 'Prep', age: '5–6 years', color: 'green', icon: '🪐', description: 'Grow reading & reasoning skills' },
];

function App() {
  const [store, setStore] = useState<Store>(loadStore); const [screen, setScreen] = useState<Screen>('profiles'); const [sound, setSound] = useState(true); const [currentIndex, setCurrentIndex] = useState(0); const [selectedActivityId, setSelectedActivityId] = useState('abc-adventure'); const [memoryRound, setMemoryRound] = useState(0); const [selectedAnswer, setSelectedAnswer] = useState<boolean | null>(null); const [transitioning, setTransitioning] = useState(false); const [optionSession, setOptionSession] = useState<Record<string, ShuffledQuestion>>({}); const countTimer = useRef<number | null>(null); const countAnswerLock = useRef(false); const [showPin, setShowPin] = useState(false); const [showRestart, setShowRestart] = useState(false); const [editingProfile, setEditingProfile] = useState<Profile | null>(null); const [formReturn, setFormReturn] = useState<Screen>('profiles');
  const voice = useVoice(); const active = store.profiles.find((profile) => profile.id === store.activeProfileId) || store.profiles[0]; const language = active?.language || 'en'; const activities = activitiesFor(active?.classLevel || 'Pre-Nursery', language); const selectedActivity = activities.find((activity) => activity.id === selectedActivityId) || activities[0]; const questions = selectedActivity?.tasks || []; const allActivityTasks = activities.flatMap((activity) => activity.tasks); const completedActivities = activities.filter((activity) => activity.tasks.length > 0 && activity.tasks.every((item) => active?.completedTaskIds.includes(item.id))).length; const profile = active ? { ...active, dailyCompleted: completedActivities } : newProfile('Little Star', 'Pre-Nursery'); const safeIndex = questions.length ? Math.max(0, Math.min(currentIndex, questions.length - 1)) : 0; const task = questions[safeIndex];
  useEffect(() => saveStore(store), [store]);
  useEffect(() => { document.documentElement.lang = language === 'ur' ? 'ur' : 'en'; document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr'; }, [language]);
  useEffect(() => { voice.setEnabled(sound && profile.voice.enabled); }, [sound, profile.voice.enabled, voice]);
  useEffect(() => { if (active && active.dailyTaskIds.length === 0) setStore((old) => ({ ...old, profiles: old.profiles.map((item) => item.id === active.id ? { ...item, dailyTaskIds: allActivityTasks.map((task) => task.id) } : item) })); }, [active?.id, language, allActivityTasks.length]);
  useEffect(() => {
    voice.stop(); if (!profile.voice.autoInstructions || !task) return;
    const message = screen === 'game' ? taskText(task, language, 'instruction') : screen === 'complete' ? (language === 'ur' ? `مبارک ہو ${profile.name}! آپ نے مہم مکمل کر لی ہے۔` : `Congratulations, ${profile.name}! You completed the adventure.`) : screen === 'adventure' ? (language === 'ur' ? `${profile.name}، ایک سرگرمی منتخب کریں۔` : `${profile.name}, choose an activity.`) : screen === 'map' ? (language === 'ur' ? 'اپنی اگلی مہم منتخب کریں۔' : 'Choose your next adventure.') : '';
    if (message) voice.speak(message, language, { key: `${screen}-${task.id}-${safeIndex}-${language}`, speed: profile.voice.speed, volume: profile.voice.volume });
  }, [screen, safeIndex, task?.id, language, profile.name]);
  const updateActive = (next: Partial<Profile>) => { if (!active) return; setStore((old) => ({ ...old, profiles: old.profiles.map((item) => item.id === active.id ? { ...item, ...next } : item) })); };
  const clearCountTimer = () => { if (countTimer.current !== null) { window.clearTimeout(countTimer.current); countTimer.current = null; } };
  useEffect(() => () => clearCountTimer(), []);
  const changeLanguage = (next: 'en' | 'ur') => { if (next === language) return; clearCountTimer(); countAnswerLock.current = false; voice.stop(); const nextActivities = activitiesFor(active?.classLevel || 'Pre-Nursery', next); const nextActivity = nextActivities.find((item) => item.id === selectedActivityId) || nextActivities[0]; const nextIndex = nextActivity.id === 'count-stars' || nextActivity.id === 'urdu-count-stars' ? Math.max(0, Math.min(currentIndex, nextActivity.tasks.length - 1)) : 0; setSelectedActivityId(nextActivity.id); setOptionSession(buildShuffledSession(nextActivity.tasks, nextIndex)); setCurrentIndex(nextIndex); setSelectedAnswer(null); setTransitioning(false); updateActive({ language: next, resumePosition: 0 }); };
  const chooseProfile = (id: string) => { voice.unlock(); setStore((old) => ({ ...old, activeProfileId: id })); setScreen('splash'); };
  const selectLevel = (level: ClassLevel) => { const nextActivities = activitiesFor(level, language); setSelectedActivityId(nextActivities[0].id); setOptionSession(buildShuffledSession(nextActivities[0].tasks)); updateActive({ classLevel: level, dailyTaskIds: nextActivities.flatMap((activity) => activity.tasks).map((item) => item.id), dailyCompleted: 0, resumePosition: 0 }); setCurrentIndex(0); setSelectedAnswer(null); setScreen('map'); };
  const startActivity = (activityId: string, index = 0) => { clearCountTimer(); countAnswerLock.current = false; const nextActivity = activities.find((item) => item.id === activityId) || activities[0]; if (!nextActivity) return; voice.unlock(); const safeStart = Math.max(0, Math.min(index, nextActivity.tasks.length - 1)); setSelectedActivityId(nextActivity.id); setOptionSession(buildShuffledSession(nextActivity.tasks, safeStart)); setMemoryRound((round) => round + 1); setCurrentIndex(safeStart); setSelectedAnswer(null); setTransitioning(false); setScreen('game'); };
  const answer = (optionId: string) => { if (transitioning || selectedAnswer !== null || !task) return; const correct = optionId === task.answerId; setSelectedAnswer(correct); updateActive({ attempts: profile.attempts + 1, accuracy: correct ? Math.min(100, Math.round(((profile.accuracy * profile.attempts) + 100) / (profile.attempts + 1))) : Math.round((profile.accuracy * profile.attempts) / (profile.attempts + 1)) }); voice.unlock(); voice.speak(correct ? taskText(task, language, 'success') : taskText(task, language, 'retry'), language, { key: `answer-${task.id}-${correct}`, speed: profile.voice.speed, volume: profile.voice.volume }); };
  const nextQuestion = () => { if (transitioning || selectedAnswer !== true || !task) return; setTransitioning(true); voice.stop(); const alreadyCompleted = profile.completedTaskIds.includes(task.id); const final = safeIndex >= questions.length - 1; const completedIds = alreadyCompleted ? profile.completedTaskIds : [...profile.completedTaskIds, task.id]; const nextCompletedIds = new Set(completedIds); const completedActivityCount = activities.filter((activity) => activity.tasks.length > 0 && activity.tasks.every((item) => nextCompletedIds.has(item.id))).length; updateActive({ stars: profile.stars + (alreadyCompleted ? 0 : task.reward), coins: profile.coins + (alreadyCompleted ? 0 : task.coins), completed: profile.completed + (alreadyCompleted ? 0 : 1), completedTaskIds: completedIds, dailyCompleted: completedActivityCount, resumePosition: final ? 0 : safeIndex + 1, badges: final && !profile.badges.includes('Daily Explorer') ? [...profile.badges, 'Daily Explorer'] : profile.badges, lastPlayedActivity: selectedActivity.title }); if (final) { setSelectedAnswer(null); setScreen('complete'); } else { setCurrentIndex(safeIndex + 1); setSelectedAnswer(null); setTransitioning(false); } };
  const resetGame = () => { clearCountTimer(); countAnswerLock.current = false; voice.stop(); setShowRestart(false); setOptionSession(buildShuffledSession(questions)); setMemoryRound((round) => round + 1); setCurrentIndex(0); setSelectedAnswer(null); setTransitioning(false); updateActive({ resumePosition: 0, lastPlayedActivity: selectedActivity.title }); setScreen('game'); };
  const completeSpecialActivity = (attempts: number) => { const completionTask = selectedActivity.tasks[0]; const alreadyCompleted = selectedActivity.tasks.every((item) => profile.completedTaskIds.includes(item.id)); const completedIds = alreadyCompleted ? profile.completedTaskIds : [...new Set([...profile.completedTaskIds, ...selectedActivity.tasks.map((item) => item.id)])]; const nextCompletedIds = new Set(completedIds); const completedActivityCount = activities.filter((activity) => activity.tasks.length > 0 && activity.tasks.every((item) => nextCompletedIds.has(item.id))).length; updateActive({ stars: profile.stars + (alreadyCompleted ? 0 : completionTask.reward), coins: profile.coins + (alreadyCompleted ? 0 : completionTask.coins), completed: profile.completed + (alreadyCompleted ? 0 : 1), completedTaskIds: completedIds, dailyCompleted: completedActivityCount, lastPlayedActivity: selectedActivity.title, attempts: profile.attempts + attempts }); setSelectedAnswer(null); setScreen('complete'); setTransitioning(false); };
  const countAnswer = (optionId: string) => { if (countAnswerLock.current || transitioning || selectedAnswer !== null || !task || task.visualCount === undefined) return; countAnswerLock.current = true; const correct = optionId === task.answerId; setSelectedAnswer(correct); voice.unlock(); voice.speak(correct ? taskText(task, language, 'success') : taskText(task, language, 'retry'), language, { key: `count-answer-${task.id}-${correct}`, speed: profile.voice.speed, volume: profile.voice.volume }); clearCountTimer(); if (correct) { setTransitioning(true); const taskId = task.id; countTimer.current = window.setTimeout(() => { countTimer.current = null; if (taskId !== questions[safeIndex]?.id) { countAnswerLock.current = false; setTransitioning(false); return; } if (safeIndex >= questions.length - 1) completeSpecialActivity(1); else { countAnswerLock.current = false; setCurrentIndex(safeIndex + 1); setSelectedAnswer(null); setTransitioning(false); } }, 1200); } else { setTransitioning(true); countTimer.current = window.setTimeout(() => { countTimer.current = null; countAnswerLock.current = false; setSelectedAnswer(null); setTransitioning(false); }, 500); } };
  const nextActivity = () => { const index = activities.findIndex((activity) => activity.id === selectedActivity.id); startActivity(activities[(index + 1) % activities.length].id); };
  const saveProfile = (draft: { name: string; avatar: string; classLevel: ClassLevel; age?: string }) => { if (editingProfile) setStore((old) => ({ ...old, profiles: old.profiles.map((item) => item.id === editingProfile.id ? { ...item, ...draft } : item) })); else { const created = newProfile(draft.name, draft.classLevel, draft.avatar, draft.age); setStore((old) => ({ ...old, profiles: [...old.profiles, created], activeProfileId: created.id })); } setEditingProfile(null); setScreen(formReturn); };
  const openParent = () => setShowPin(true);
  return <div className="app-shell"><Header language={language} sound={sound} onSound={() => { setSound(!sound); voice.setEnabled(!sound); }} onLanguageChange={changeLanguage} onParent={openParent} onHome={() => setScreen(active ? 'map' : 'profiles')} /><div className="utility-bar"><ShareButton compact /><QRShare /><InstallButton /><VoiceControls language={language} preferences={profile.voice} onPreferencesChange={(next) => updateActive({ voice: next })} compact /><button className="privacy-link" onClick={() => setScreen('privacy')}>{uiText(language, 'privacy')}</button></div><main className="main-content">
    {screen === 'profiles' && <ProfilePicker profiles={store.profiles} language={language} onSelect={chooseProfile} onAdd={() => { setEditingProfile(null); setFormReturn('profiles'); setScreen('profile-form'); }} onEdit={(item) => { setEditingProfile(item); setFormReturn('profiles'); setScreen('profile-form'); }} onDelete={(id) => { if (store.profiles.length > 1) setStore((old) => ({ ...old, profiles: old.profiles.filter((item) => item.id !== id) })); }} />}
    {screen === 'profile-form' && <ProfileForm profile={editingProfile} onBack={() => setScreen(formReturn)} onSave={saveProfile} />}{screen === 'privacy' && <PrivacyPage onBack={() => setScreen('profiles')} />}{screen === 'splash' && <Splash name={profile.name} onStart={() => setScreen('levels')} />}{screen === 'levels' && <LevelPicker selected={profile.classLevel} onBack={() => setScreen('splash')} onSelect={selectLevel} />}{screen === 'map' && <Island profile={profile} onBack={() => setScreen('levels')} onPlay={() => setScreen('adventure')} />}{screen === 'adventure' && <AdventureBoard profile={profile} activities={activities} onBack={() => setScreen('map')} onPlay={startActivity} />}
    {screen === 'game' && task && <><ActivityActions language={language} onBack={() => { clearCountTimer(); voice.stop(); setScreen('adventure'); }} onRestart={() => { clearCountTimer(); setShowRestart(true); }} onSwitch={() => { clearCountTimer(); voice.stop(); updateActive({ lastPlayedActivity: 'In Progress' }); setScreen('adventure'); }} />{selectedActivity.id === 'count-stars' || selectedActivity.id === 'urdu-count-stars' ? <CountStarsGame task={task} options={optionSession[task.id]?.options || task.options} language={language} index={safeIndex} total={questions.length} result={selectedAnswer} transitioning={transitioning} preferences={profile.voice} onAnswer={countAnswer} onReplay={() => { voice.unlock(); voice.speak(taskText(task, language, 'instruction'), language, { key: `listen-${task.id}-${Date.now()}`, speed: profile.voice.speed, volume: profile.voice.volume }); }} /> : selectedActivity.game === 'memory' ? <MemoryGame key={`${selectedActivity.id}-${memoryRound}`} language={language} pairs={selectedActivity.memoryPairs || []} preferences={profile.voice} round={memoryRound} onComplete={completeSpecialActivity} /> : <Game task={task} options={optionSession[task.id]?.options || task.options} language={language} index={safeIndex} total={questions.length} result={selectedAnswer} onAnswer={answer} onReplay={() => { voice.unlock(); voice.speak(taskText(task, language, 'instruction'), language, { key: `listen-${task.id}-${Date.now()}`, speed: profile.voice.speed, volume: profile.voice.volume }); }} onStop={voice.stop} onNext={nextQuestion} transitioning={transitioning} />}</>}
    {screen === 'complete' && <Complete language={language} profile={profile} onNext={nextActivity} onPlayAgain={resetGame} onChoose={() => { setCurrentIndex(0); setSelectedAnswer(null); setScreen('adventure'); }} onMap={() => setScreen('map')} onParent={openParent} />}
    {screen === 'parent' && <><ParentDashboard profiles={store.profiles} activeId={active?.id || ''} onBack={() => setScreen('map')} onSelect={chooseProfile} onAdd={() => { setEditingProfile(null); setFormReturn('parent'); setScreen('profile-form'); }} onEdit={(item) => { setEditingProfile(item); setFormReturn('parent'); setScreen('profile-form'); }} onDelete={() => undefined} onAssign={(item) => updateActive({ assignedTasks: [...profile.assignedTasks, item] })} /><ParentVoiceSettings profile={profile} onUpdate={updateActive} /></>}
  </main><UpdateNotice />{showPin && <SecurePinModal pinHash={store.parentPinHash} onClose={() => setShowPin(false)} onSetPin={async (pin) => { const parentPinHash = await hashPin(pin); setStore((old) => ({ ...old, parentPinHash })); }} onSuccess={() => { setShowPin(false); setScreen('parent'); }} />}{showRestart && <RestartModal language={language} onClose={() => setShowRestart(false)} onRestart={resetGame} />}</div>;
}

function Header({ language, sound, onSound, onLanguageChange, onParent, onHome }: { language: LanguageMode; sound: boolean; onSound: () => void; onLanguageChange: (language: 'en' | 'ur') => void; onParent: () => void; onHome: () => void }) { return <header className="topbar"><button className="brand" onClick={onHome}><span className="brand-mark">★</span><span>little<span>stars</span></span></button><div className="global-language-switch language-switch" aria-label="Language selector"><button className={language === 'en' ? 'selected' : ''} onClick={() => onLanguageChange('en')}>English</button><button className={language === 'ur' ? 'selected' : ''} onClick={() => onLanguageChange('ur')} dir="rtl">اردو</button></div><div className="top-actions"><button className="icon-btn" aria-label={language === 'ur' ? 'آواز بدلیں' : 'Toggle sound'} onClick={onSound}>{sound ? <Volume2 size={20} /> : <VolumeX size={20} />}</button><button className="parent-link" onClick={onParent}><LockKeyhole size={16} /> {uiText(language, 'parentZone')}</button></div></header>; }
function Splash({ name, onStart }: { name: string; onStart: () => void }) { return <section className="splash page-center"><div className="mascot mascot-large">🦊</div><p className="eyebrow">Welcome back, {name}!</p><h1>Little Stars<br /><em>Learning Adventure</em></h1><p className="lead">Big discoveries for little minds.<br />Let’s explore together!</p><button className="primary-btn jumbo" onClick={onStart}>{name}, start adventure <ArrowRight size={22} /></button><div className="safe-note"><ShieldCheck size={16} /> A safe, ad-free learning world</div></section>; }
function LevelPicker({ onBack, onSelect, selected }: { onBack: () => void; onSelect: (level: ClassLevel) => void; selected: ClassLevel }) { return <section className="page narrow-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={18} /> Back</button><div className="section-heading"><span className="sparkle-badge">✦</span><p className="eyebrow">Welcome, little explorer</p><h2>Choose your <em>learning level</em></h2></div><div className="level-grid">{levels.map((level) => <button className={`level-card ${level.color} ${selected === level.name ? 'selected' : ''}`} key={level.name} onClick={() => onSelect(level.name)}><span className="level-icon">{level.icon}</span><span className="level-copy"><strong>{level.name}</strong><small>{level.age}</small><span>{level.description}</span></span><ArrowRight /></button>)}</div></section>; }
function Island({ profile, onBack, onPlay }: { profile: Profile; onBack: () => void; onPlay: () => void }) { return <section className="page island-page"><div className="island-heading"><button className="back-btn" onClick={onBack}><ArrowLeft size={18} /> Levels</button><div><p className="eyebrow">Your learning island</p><h2>Hi, <em>{profile.name}!</em> 🌟</h2></div><div className="score-pills"><span><Star size={16} fill="currentColor" /> {profile.stars}</span><span><Coins size={16} fill="currentColor" /> {profile.coins}</span></div></div><div className="island-callout"><span className="mini-mascot">🦊</span><div><strong>Today’s adventure</strong><p>Explore letters and picture friends.</p></div><button className="primary-btn" onClick={onPlay}>Play now <Play size={16} fill="currentColor" /></button></div></section>; }
function ActivityActions({ language, onBack, onRestart, onSwitch }: { language: LanguageMode; onBack: () => void; onRestart: () => void; onSwitch: () => void }) { const voice = useVoice(); return <><div className="activity-actions" dir={language === 'ur' ? 'rtl' : 'ltr'}><button className="secondary-btn" onClick={onBack}><ArrowLeft size={16} /> {language === 'ur' ? 'واپس' : 'Back'}</button><button className="secondary-btn" onClick={onRestart}><RotateCcw size={16} /> {language === 'ur' ? 'دوبارہ شروع کریں' : 'Restart'}</button><button className="secondary-btn" onClick={onSwitch}><Map size={16} /> {language === 'ur' ? 'سرگرمی تبدیل کریں' : 'Switch Activity'}</button></div>{import.meta.env.DEV && <small className="voice-note" data-testid="voice-diagnostic">language={language} · selectedEnglish={voice.diagnostic.englishVoice} ({voice.diagnostic.englishLang}) · selectedUrdu={voice.diagnostic.urduVoice} ({voice.diagnostic.urduLang})</small>}</>; }
function Game({ task, options, language, index, total, result, transitioning, onAnswer, onReplay, onStop, onNext }: { task: Task; options: Task['options']; language: LanguageMode; index: number; total: number; result: boolean | null; transitioning: boolean; onAnswer: (optionId: string) => void; onReplay: () => void; onStop: () => void; onNext: () => void }) { const number = Math.max(1, Math.min(index + 1, total)); return <section className="page game-page" dir={language === 'ur' ? 'rtl' : 'ltr'}><div className="game-top"><span className="game-stars"><Star size={18} fill="currentColor" /> {number} / {total}</span><div className="question-progress">{Array.from({ length: total }, (_, i) => <span className={i < number ? 'filled' : ''} key={i} />)}</div></div><div className="game-card"><div className="instruction-row"><button className="round-btn" onClick={onReplay} aria-label={uiText(language, 'listenAgain')}>🔊</button><span>{number} / {total}</span><button className="round-btn" onClick={onStop} aria-label={uiText(language, 'stop')}>■</button></div><div className="letter-orb"><span>{task.letter || '⭐'}</span><small>{language === 'ur' ? 'حرف' : 'Letter'}</small></div><h2>{taskText(task, language, 'instruction')}</h2><p className="hint"><CircleHelp size={17} /> {taskText(task, language, 'hint')}</p><div className="option-grid">{options.map((option) => <button key={option.id} className={`picture-option ${result !== null && option.id === task.answerId ? 'correct-option' : ''}`} onClick={() => onAnswer(option.id)} disabled={result !== null || transitioning}><span>{option.emoji}</span><strong>{language === 'ur' ? option.wordUr : option.word}</strong></button>)}</div>{result !== null && <div className={`feedback ${result ? 'good' : 'try-again'}`}><span>{result ? '🌟' : '💛'}</span><div><strong>{result ? uiText(language, 'excellent') : uiText(language, 'tryAgain')}</strong><p>{result ? taskText(task, language, 'success') : taskText(task, language, 'retry')}</p></div>{result && <button className="primary-btn" disabled={transitioning} onClick={onNext}>{index === total - 1 ? uiText(language, 'finish') : uiText(language, 'next')} <ArrowRight size={17} /></button>}</div>}</div><div className="game-footer"><VoiceControls language={language} preferences={{ enabled: true, autoInstructions: true, speed: 'normal', volume: 1 }} compact={false} /><button className="text-btn" onClick={onReplay}><Volume2 size={17} /> {uiText(language, 'listenAgain')}</button></div>{import.meta.env.DEV && <small className="voice-note" data-testid="voice-diagnostic">language={language} · question={task.id} · currentIndex={index} · total={total}</small>}</section>; }
function Complete({ language, profile, onNext, onPlayAgain, onChoose, onMap, onParent }: { language: LanguageMode; profile: Profile; onNext: () => void; onPlayAgain: () => void; onChoose: () => void; onMap: () => void; onParent: () => void }) { return <section className="page complete-page page-center" dir={language === 'ur' ? 'rtl' : 'ltr'}><div className="confetti">✦ ✧ ✦ ✧ ✦</div><div className="mascot mascot-medium">🦊</div><p className="eyebrow">{language === 'ur' ? 'مہم مکمل' : 'Adventure complete'}</p><h1>{language === 'ur' ? `${profile.name}، آپ ستارے ہیں!` : <>You’re a <em>star!</em></>}</h1><div className="reward-card"><div><Star size={23} fill="currentColor" /><strong>+{profile.stars}</strong><small>{language === 'ur' ? 'ستارے' : 'Stars'}</small></div><div><Coins size={23} fill="currentColor" /><strong>+{profile.coins}</strong><small>{language === 'ur' ? 'سکے' : 'Coins'}</small></div></div><div className="completion-actions"><button className="primary-btn" onClick={onNext}>{language === 'ur' ? 'اگلی سرگرمی' : 'Next Activity'} <ArrowRight size={17} /></button><button className="secondary-btn" onClick={onPlayAgain}>{language === 'ur' ? 'دوبارہ کھیلیں' : 'Play Again'} <RotateCcw size={17} /></button><button className="secondary-btn" onClick={onChoose}>{language === 'ur' ? 'دوسری سرگرمی منتخب کریں' : 'Choose Another Activity'} <BookOpen size={17} /></button><button className="secondary-btn" onClick={onMap}>{language === 'ur' ? 'جزیرے پر واپس جائیں' : 'Back to Island'} <Map size={17} /></button><button className="text-btn" onClick={onParent}><BarChart3 size={17} /> {language === 'ur' ? 'والدین کی رپورٹ' : 'Parent Progress'}</button></div></section>; }
function RestartModal({ language, onClose, onRestart }: { language: LanguageMode; onClose: () => void; onRestart: () => void }) { return <div className="modal-backdrop"><div className="pin-modal" dir={language === 'ur' ? 'rtl' : 'ltr'}><button className="modal-close" onClick={onClose}><X /></button><h2>{language === 'ur' ? 'کیا آپ یہ سرگرمی دوبارہ شروع کرنا چاہتے ہیں؟' : 'Restart this activity?'}</h2><p>{language === 'ur' ? 'اس سرگرمی کی موجودہ پیش رفت ختم ہو جائے گی۔' : 'Your current activity progress will reset.'}</p><div className="button-stack"><button className="primary-btn" onClick={onRestart}>{language === 'ur' ? 'دوبارہ شروع کریں' : 'Restart'} <RotateCcw size={17} /></button><button className="secondary-btn" onClick={onClose}>{language === 'ur' ? 'منسوخ کریں' : 'Cancel'}</button></div></div></div>; }
function SecurePinModal({ pinHash, onClose, onSetPin, onSuccess }: { pinHash: string | null; onClose: () => void; onSetPin: (pin: string) => Promise<void>; onSuccess: () => void }) { const [pin, setPin] = useState(''); const [confirm, setConfirm] = useState(''); const setup = !pinHash; const submit = async () => { if (!/^\d{4}$/.test(pin) || (setup && pin !== confirm)) return; if (setup) { await onSetPin(pin); onSuccess(); } else if ((await hashPin(pin)) === pinHash) onSuccess(); }; return <div className="modal-backdrop"><div className="pin-modal"><button className="modal-close" onClick={onClose}><X /></button><span className="lock-circle"><LockKeyhole /></span><h2>{setup ? 'Create parent PIN' : 'Grown-up zone'}</h2><input autoFocus type="password" maxLength={4} value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, ''))} />{setup && <input type="password" maxLength={4} value={confirm} onChange={(event) => setConfirm(event.target.value.replace(/\D/g, ''))} />}<button className="primary-btn" onClick={submit}>{setup ? 'Save PIN' : 'Unlock dashboard'} <ShieldCheck size={17} /></button></div></div>; }
function ErrorBoundary({ children }: { children: ReactNode }) { return <>{children}</>; }
const root = document.getElementById('root'); if (!root) throw new Error('Little Stars root element is missing'); createRoot(root).render(<VoiceProvider><ErrorBoundary><App /></ErrorBoundary></VoiceProvider>);
if ('serviceWorker' in navigator) window.addEventListener('load', () => { navigator.serviceWorker.register('/sw.js').catch(() => undefined); });
