import { Check, Mic2, RotateCcw, Volume2 } from 'lucide-react';
import type { Profile, VoicePreferences } from './storage';
import { languageLabels, useVoice } from './voice';

export function ParentVoiceSettings({ profile, onUpdate }: { profile: Profile; onUpdate: (next: Partial<Profile>) => void }) {
  const voice = useVoice(); const updateVoice = (next: Partial<VoicePreferences>) => onUpdate({ voice: { ...profile.voice, ...next } });
  const testEnglish = () => { voice.unlock(); voice.speak(`Hello ${profile.name}! Voice guidance is ready.`, 'en', { key: `test-en-${Date.now()}`, speed: profile.voice.speed, volume: profile.voice.volume }); };
  const testUrdu = () => { voice.unlock(); voice.speak('السلام علیکم! اردو آواز کا امتحان کریں۔', 'ur', { key: `test-ur-${Date.now()}`, speed: profile.voice.speed, volume: profile.voice.volume }); };
  return <article className="panel voice-settings-panel" dir={profile.language === 'ur' ? 'rtl' : 'ltr'}>
    <div className="panel-heading"><div><p className="eyebrow">For grown-ups</p><h3>Voice & language</h3></div><span><Mic2 size={15} /> Child-friendly audio</span></div>
    <p className="panel-note">Voice guidance helps children play even if they cannot read yet.</p>
    <div className="language-grid">{(['en', 'ur'] as const).map((option) => <button key={option} className={profile.language === option ? 'language-card selected' : 'language-card'} onClick={() => { onUpdate({ language: option }); voice.stop(); voice.unlock(); voice.speak(languageLabels[option].sample[option], option, { key: `language-sample-${option}-${Date.now()}`, speed: profile.voice.speed, volume: profile.voice.volume }); }}><span className="language-speaker">{profile.language === option ? <Check size={18} /> : <Volume2 size={18} />}</span><strong>{languageLabels[option].title}</strong><small>{languageLabels[option].subtitle}</small></button>)}</div>
    <div className="voice-setting-row"><label><input type="checkbox" checked={profile.voice.enabled} onChange={(event) => { updateVoice({ enabled: event.target.checked }); voice.setEnabled(event.target.checked); }} /> Voice on</label><label><input type="checkbox" checked={profile.voice.autoInstructions} onChange={(event) => updateVoice({ autoInstructions: event.target.checked })} /> Automatic instructions</label></div>
    <div className="voice-setting-row"><label>Voice speed<select value={profile.voice.speed} onChange={(event) => updateVoice({ speed: event.target.value as VoicePreferences['speed'] })}><option value="slow">Slow</option><option value="normal">Normal</option></select></label><label>Volume<input type="range" min="0" max="1" step="0.05" value={profile.voice.volume} onChange={(event) => updateVoice({ volume: Number(event.target.value) })} /></label></div>
    <div className="voice-actions"><button className="secondary-btn" onClick={testEnglish}><Volume2 size={17} /> Test English Voice</button><button className="secondary-btn" onClick={testUrdu}><Volume2 size={17} /> اردو آواز آزمائیں</button><button className="text-btn" onClick={() => { updateVoice({ enabled: true, autoInstructions: true, speed: 'normal', volume: 0.85 }); voice.setEnabled(true); }}><RotateCcw size={16} /> Reset audio preferences</button></div>
    <div className="voice-selection" aria-live="polite"><label>Selected English voice<select value={voice.diagnostic.englishVoice} disabled><option>{voice.diagnostic.englishVoice} ({voice.diagnostic.englishLang})</option></select></label><label dir="rtl">منتخب اردو آواز<select value={voice.diagnostic.urduVoice} disabled><option>{voice.diagnostic.urduVoice} ({voice.diagnostic.urduLang})</option></select></label></div>
    <small className="voice-note">English: {voice.diagnostic.englishVoice} ({voice.diagnostic.englishLang})<br />Urdu: {voice.diagnostic.urduVoice} ({voice.diagnostic.urduLang})</small>
    {!voice.urduVoiceAvailable && <small className="voice-warning" dir="rtl">اس ڈیوائس میں اردو آواز دستیاب نہیں۔ براہِ کرم اردو وائس انسٹال کریں۔</small>}
  </article>;
}
